# Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Tavis Jiang"
title_separator          : "-"
name                     : "蒋勃琛 (Tavis Jiang)"
description              : "SJTU CS Undergraduate | Linux & AI Enthusiast"
url                      : "https://tavis-jiang.github.io"
baseurl                  : ""
repository               : "tavis-jiang/tavis-jiang.github.io"

# Site Author (控制侧边栏)
author:
  avatar           : "profile.png" # 请确认根目录有此文件
  name             : "蒋勃琛 (Tavis Jiang)"
  bio              : "SJTU 24级本科生 | Linux (Fedora) & Vim 用户"
  location         : "Shanghai, China"
  employer         : "Shanghai Jiao Tong University"
  uri              : "https://tavis-jiang.github.io"
  email            : "24jiangbc@sjtu.edu.cn"
  github           : "tavis-jiang"
  # 社交媒体 (如有请填写用户名，没有请保持空白)
  linkedin         : 
  twitter          : 
  googlescholar    : 
  orcid            : 

# 下面这些是保持界面一致性的关键配置，不要删除
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - node_modules

markdown: kramdown
highlighter: rouge

collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
